name: sawo_sdk
description: Passwordless and OTP-less Authentication for your website. It helps you to authenticate user via their email or phone number.
version: 0.1.3
homepage: https://github.com/sawolabs/flutter_sdk

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  internet_connection_checker: ^0.0.1+3
  uuid: ^3.0.5
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sawolabs.sawosdk.sawo_sdk
        pluginClass: SawoSdkPlugin
      ios:
        pluginClass: SawoSdkPlugin
